name: my-home

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=my_home
    volumes:
      - my_home_pg_data:/bitnami/postgresql

volumes:
  my_home_pg_data:
